version: '2'

services:
  frontend:
    image: molkakardoun/molkakardoun_5se1-grp4-dancescapefront:latest
    restart: unless-stopped
    ports:
      - "4200:80"  # Map port 4200 on the host to port 80 in the container (Nginx serves on port 80)
    volumes:
      - .:/frontend  # Optional: mount the current directory for live updates
      - /frontend/node_modules  # Avoid mounting node_modules
      - /frontend/cache:/root/.npm
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge
