#docker-compose.yml// pour le front
version: '3.8'

services:
  frontend:
    build:
      context: .  # Utiliser le répertoire actuel comme contexte de build
      dockerfile: Dockerfile  # Spécifier le Dockerfile pour le frontend
    ports:
      - "4200:80"  # Mapper le port 4200 de l'hôte vers le port 80 dans le conteneur (Nginx sert sur le port 80)
    volumes:
      - .:/frontend  # Optionnel : monter le répertoire actuel pour les mises à jour en direct
      - /frontend/node_modules  # Éviter de monter node_modules
    networks:
      - app-network  # Ajouter le réseau partagé avec le backend
      - frontend-network  # Garder le réseau du frontend si nécessaire

networks:
  app-network:
    external: true  # Utiliser le réseau existant du backend
  frontend-network:
    driver: bridge
