sonar.projectKey=front_dance
sonar.projectName=front_dance
sonar.sources=src
sonar.exclusions=**/*.spec.ts,**/node_modules/**
sonar.host.url=http://192.168.33.10:9000
sonar.login=162af7ab3a082f01a4d00170e79487a9b6426feb
