sonar.projectKey=dance_projectfront
sonar.projectName=dance_projectfront
sonar.sources=src
sonar.exclusions=**/*.spec.ts,**/node_modules/**
sonar.host.url=http://192.168.33.10:9000
sonar.login=f84d00012e1aaf6dcfdcd4144fa8279c1ec3e765
