// ShippingType.model.ts

export enum ShippingType {
    INTERNATIONAL_SHIPPING = 'INTERNATIONAL_SHIPPING',
    HYBRID_SHIPPING_SERVICES = 'HYBRID_SHIPPING_SERVICES',
    FREE_SHIPPING = 'FREE_SHIPPING',
    FEDEX = 'FEDEX'
  }
  